# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build test

on:
  workflow_dispatch:
  push:
    branches: 
      - main
      - dev
  pull_request:
    branches: 
      - "*"

defaults:
  run:
    working-directory: ./block

env:
  CI: false

jobs:
  build-block:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    name: Build using Node ${{ matrix.node-version }}
    steps:
    - uses: actions/checkout@v3
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Run npm install
      run: npm ci
    # - run: npm run build --if-present
    # - run: npm test --passWithNoTests
    - name: Install truffle
      run: npm install truffle -g
    - name: Install and run Ganache
      run: |
        npm install ganache -g
        ganache -p=65534 -m="lonely initial gold insect blue path episode kingdom fame execute ranch velvet" -D
    - name: Run truffle tests
      run: truffle test
      
